package com.dingmouren.easymvp.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.dingmouren.easymvp.bean.GankResultWelfare;

import com.dingmouren.easymvp.bean.GankResultWelfareDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gankResultWelfareDaoConfig;

    private final GankResultWelfareDao gankResultWelfareDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gankResultWelfareDaoConfig = daoConfigMap.get(GankResultWelfareDao.class).clone();
        gankResultWelfareDaoConfig.initIdentityScope(type);

        gankResultWelfareDao = new GankResultWelfareDao(gankResultWelfareDaoConfig, this);

        registerDao(GankResultWelfare.class, gankResultWelfareDao);
    }
    
    public void clear() {
        gankResultWelfareDaoConfig.clearIdentityScope();
    }

    public GankResultWelfareDao getGankResultWelfareDao() {
        return gankResultWelfareDao;
    }

}
